### ISSUE TITLE
Spec file variables

### ISSUE THREAD

**Issue by drognisep** [drognisep/sshtail#12]
It would be nice to add the possibility to include variables based on values that have already been configured.

**Example:**
```yaml
hosts:
  host-1:
    hostname: some-host-1
    file: /var/log/applogs/{{ hostname }}_20200803.log
```
